name: Push to EpitechRepo

on:
  push:
    branches:
      - main

jobs:
  push_to_EpitechRepo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout OriginalRepo
      uses: actions/checkout@v2

    - name: Push to EpitechRepo
      run: |
        git config user.name "ian-dqn"
        git config user.email "ian.duquennoi@epitech.eu"
        git remote add T-WEB-700-PAR_30 https://github.com/EpitechMscProPromo2025/T-WEB-700-PAR_30.git/
        git push T-WEB-700-PAR_30 main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
